Дан список из кортежей temps. На первом месте в кортеже указан год в виде строки, а на втором — средняя температура января в Петербурге в указанном году.

Напишите функцию check(temps), которая будет выводить словарь, в котором ключи — годы, а значения — показатели температуры. Ключи необходимо отсортировать в порядке убывания соответствующих им температур.

Пример списка temps:

temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]

Пример вывода:

OrderedDict([('2001', -2.5), ('2000', -4.4), ('2002', -4.4), ('2003', -9.5)])

In [4]:
from collections import OrderedDict
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]
def check(temps):
    c = OrderedDict(sorted(temps, key = lambda x: x[1], reverse = True))
    #od = OrderedDict(c)
    #od = str(od)
    print(c)

Напишите функцию brackets(line), которая определяет, является ли последовательность из круглых скобок line правильной.

Примечание 1. Какая последовательность скобок правильная?

Правильной скобочной последовательностью назовём такую последовательность скобок, в которой для каждой открывающей скобки есть последующая соответствующая ей закрывающая скобка. Соответственно, остальные скобочные последовательности назовём неправильными. Пустую строку будем считать правильной последовательностью.

Примечание 2.Для решения этой задачи потребуется использовать стек.

Посимвольно переберите строку. Если встретилась открывающаяся скобка, положите её в стек. Если встретилась закрывающаяся скобка, извлеките скобку из стека.

Если стек пустой, то есть извлечь скобку нельзя, последовательность неправильная.
Если строка закончилась и стек стал пустым, последовательность правильная.
Если в стеке остались скобки, последовательность неправильная.
Пример


print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False

In [6]:
from collections import deque

def brackets(line):
    temp = deque()
   
    for symbol in line:
        if symbol =='(' :
            temp.append(symbol)             
        elif symbol == ')' and len(temp) > 0:
            del temp[0]         
        elif symbol == ')' and len(temp) == 0:
            return False
    if len(temp) == 0:
        return True
    else:
        return False
print(brackets("(()())"))

True


Дан список кортежей ratings с рейтингами кафе. Кортеж состоит из названия и рейтинга кафе.

Необходимо отсортировать кортеж по убыванию рейтинга. Если рейтинги совпадают, то отсортировать кафе дополнительно по названию в алфавитном порядке.

Получите словарь cafes с упорядоченными ключами из отсортированного списка, где ключи — названия кафе, а значения — их рейтинг.
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]


In [ ]:
from collections import OrderedDict

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]


cafes = OrderedDict(sorted(ratings, key = lambda x : (-x[1], x[0])))

Напишите функцию task_manager(tasks), которая принимает список задач tasks для нескольких серверов. Каждый элемент списка состоит из кортежа (<номер задачи>, <название сервера>, <высокий приоритет задачи>).

Функция должна создавать словарь и заполнять его задачами по следующему принципу: название сервера — ключ, по которому хранится очередь задач для конкретного сервера.

Если поступает задача без высокого приоритета (последний элемент кортежа — False), добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.

Для словаря используйте defaultdict, для очереди — deque.

Функция возвращает полученный словарь с задачами.

Пример
tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})


In [7]:
from collections import deque
from collections import defaultdict

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]
finaly_dyct = defaultdict(deque)


def task_manager(tasks):
    dq_1 = deque()
    dq_2 = deque()
    for elements in tasks:
        if elements[1] == 'voltage':
            if elements[2] == True:
                dq_1.appendleft(elements[0])
            else:
                dq_1.append(elements[0]) 
            finaly_dyct[elements[1]] = dq_1  
          
        elif elements[1] == 'office':
            if elements[2] == True:
                dq_2.appendleft(elements[0])
            else:
                dq_2.append(elements[0]) 
            finaly_dyct[elements[1]] = dq_2   
    return finaly_dyct
   
print(task_manager(tasks))

defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


Вам дан массив mystery

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
Выполните все пукты задания по порядку.

Пожалуйста, не меняйте названия переменных, в которых должны появиться ответы.

В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца

В переменную last сохраните элемент из последней строки последнего столбца

В переменную line_4 сохраните строку 4

В переменную col_2 сохраните предпоследний столбец

Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). Результат сохраните в переменную part

Сохраните в переменную rev последний столбец в обратном порядке

Сохраните в переменную trans транспонированный массив

In [ ]:
import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4, 2] 
#print(elem_5_3)
last = mystery[5, 6]
#print(last)
line_4 = mystery[3]
#print(line_4)
col_2 = mystery[:,5]
#print(col_2)
part = mystery[1:4, 2:5]
# print(part)
rev = mystery[:, 6][::-1]
# print(rev)
trans = mystery.transpose()
#print(trans)

Вам дан массив mystery:

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено

В переменную n_nan сохраните число пропущенных значений

Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями

Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int

Отсортируйте значения в массиве mystery по возрастанию и сохраните результат в переменную array

Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!

Например,

 1, 2, 3, 4 -> 1    3
               2    4
Сохраните в переменную col средний столбец из table

In [ ]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery)
n_nan = len(mystery[np.isnan(mystery)])

mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
#print(mystery_new, 'new')

mystery_int = np.int32(mystery)
#print(mystery_int, 'int')

array = np.sort(mystery)
#print(array, 'array')

table = array.reshape((3,5))
table = table.transpose()
#print(table)

col = table[:, 1]
#print(col)


Задайте seed = 2021.

Сохраните в переменные необходимые значения.

Примечание 1. Не меняйте названия переменных и последовательность генерации случайных чисел в задании.

Примечание 2. Не забудьте импортировать numpy и сразу задать seed = 2021

Примечание 3. Необходимый тип данных в подзаданиях — numpy.array.

В simple сохраните случайное число в диапазоне от 0 до 1

Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms

Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table

В переменную even сохраните четные числа от 2 до 16 (включительно)

Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился

Получите из even 3 числа без повторений. Сохраните их в переменную select

Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)

In [ ]:
import numpy as np
np.random.seed(2021)

simple = np.random.rand()

randoms = np.random.uniform(-150, 2021, size = 120)

table = np.random.randint(1, 101, size=(3,2), dtype=int)

even = np.arange(2,17,2)

mix = even.copy()
mix = np.random.permutation(mix)



select = np.random.choice(even, size = 3, replace = False)

triplet = np.random.permutation(select)


Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

Пример


get_chess(1)
# array([[0.]])

get_chess(4)
# array([[0., 1., 0., 1.],
#        [1., 0., 1., 0.],
#        [0., 1., 0., 1.],
#        [1., 0., 1., 0.]])

In [ ]:
import numpy as np

def get_chess(a):
    zeros_3d = np.zeros((a,a), dtype = np.float16)
    zeros_3d[1::2,::2] = 1
    zeros_3d[::2, 1::2] = 1  
    return zeros_3d
# print(get_chess(a))

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

Пример


array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)

In [13]:
# ЭТАЛОН
import numpy as np

def shuffle_seed(array):
    seed = np.random.randint(2 ** 32)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed
print(shuffle_seed(array))

ValueError: high is out of bounds for int32

In [8]:
# МОЕ РЕШЕНИЕ
import numpy as np

array = [1, 2, 3, 4, 5]

def shuffle_seed(array):

    a = np.int64(2**32-1)  
    b = np.random.randint(0,a+1)
    np.random.seed(b)
    c = np.random.choice(array, size = len(array), replace = False)
    
    return (c,b)
# выполнять в он-лайн редакторе IDE!!!
print(shuffle_seed(array))

ValueError: high is out of bounds for int32

Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

Пример
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)


In [9]:
import numpy as np

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
vec4 = np.array([41,15,6])

def min_max_dist(*vectors):
    result = []
    a_len = len(vectors)
    for vector in vectors:        
        for i in range(0, a_len):           
            if vector is vectors[i]:
                continue
            else:
                result.append(np.linalg.norm(vector - vectors[i]))
    return (min(result), max(result))

print(min_max_dist(vec1, vec2, vec3, vec4))


(5.196152422706632, 42.16633728461603)


Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

Пример

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
# True

In [10]:
import numpy as np

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

def any_normal(*vectors):
    result = []
    a_len = len(vectors)
    for vector in vectors:        
        for i in range(0, a_len):           
            if vector is vectors[i]:
                continue
            else:
                if np.dot(vector, vectors[i]) == 0:
                    return True
                else:
                    return False
    

print(any_normal(vec1, vec2, vec3))

True


Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

Пример

get_loto(3)
Результат:

array([[[ 35,  66,  38,  11,  32],
       [ 32,   7,  37,  83,  42],
       [ 89,  37,  19,  51,  89],
       [ 70, 100,  83,   5,  11],
       [ 20,  13,  60,  26,  41]],

      [[ 23,  49,  76,  44,  43],
       [ 59,  63,  99,  92,   2],
       [ 83,   4,  25,  73,  19],
       [ 10,  18,  40,  11,  21],
       [ 58,  45,  73,  93,  61]],

      [[100,  88,  70,  34,  51],
       [  5,  35,  36,  85,  88],
       [ 72,  23,  87,  30,  40],
       [ 29,  21,  51,  73,  81],
       [ 91,  19,  87,  60,  27]]])

In [11]:
import numpy as np


num = 3 
def get_loto(num) -> 'array':
    """## _summary_

    ### Args:
        - `num (_type_)`: _description_

    ### Returns:
        - `array`: _description_
    """
    # np.random.randint(0,101,size = (num,5,5), dtype = int)
    return np.random.randint(0,101,size = (num,5,5), dtype = int)

print(get_loto(num))

[[[86 52 53 23 58]
  [57 45 33 15 54]
  [20 56 39 20 90]
  [48 54 16  6 20]
  [25 72 80 92 93]]

 [[17 79  0 49 22]
  [53 67  7 89  5]
  [18 83 90 37 82]
  [15 14 31 15 19]
  [14 58 29 17 36]]

 [[19 71 31 24  1]
  [92 58 22 89 77]
  [31 10 24 34 32]
  [23 80 11 59 15]
  [65 79 74 41 91]]]


Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

Пример

get_unique_loto(3)
Результат:

array([[[26, 91, 73,  7, 16],
       [46, 85, 78, 77, 51],
       [84, 86, 55, 71, 58],
       [17, 61, 50, 30, 97],
       [66, 29, 38, 41, 32]],

      [[49, 32,  3, 21, 85],
       [45,  8, 94, 46, 96],
       [41, 38, 58, 37, 98],
       [66, 77, 54, 80, 26],
       [62, 63, 72,  5, 43]],

      [[55, 60,  6, 80, 97],
       [23, 69, 94,  9, 24],
       [17, 98, 27, 63, 79],
       [84, 74, 51, 39, 54],
       [77, 30, 48, 75, 85]]])

In [ ]:
import numpy as np

num = 2

def get_unique_loto(num):
   
    zeros_3d = np.zeros((num,5,5), dtype=np.int8)    
    for i in range(num):
        zeros_3d[i] = np.random.choice(101, size = (5,5), replace = False)
    return zeros_3d

print(get_unique_loto(num))